slack:
  token: fake_token
help:
  "(google).*? (url).*?": "https://google.com"
  "(github).*? (url).*?": "https://github.com/"
easteregg:
  jokeLevel: "10"
  triggers:
    - ".pablo*."
    - ".production*."
    - ".producion*."
    - ".produccion*."
    - ".issue*."
    - ".problema*."
   
  random-replies:
    - "When my feature demo by the sales guy went fine with no bug https://ljdchost.com/59Upfrl.gif"
    - "When I try to understand uncommented code https://ljdchost.com/UM67Vw5.gif"
    - "When a coworker quits and my knowledge transfer was too light https://ljdchost.com/1WxpJE1.gif"
    - "When I go to lunch after breaking production https://ljdchost.com/gsWcPTc.gif"
    - "When the sales guy is going to click on a bugged button in a demo https://ljdchost.com/EWTTU4M.gif"
    - "When my coffee starts working https://ljdchost.com/ZARYOC7.gif"
    - "When someone just critized my app stability https://ljdchost.com/Wnx517W.gif"
    - "When while in a business lunch I hear someone saying JavaScript is Java for the web https://ljdchost.com/nQ6iOYT.gif"
    - "When I’m taking a coffee and suddenly have an idea to fix my current bug https://ljdchost.com/k8UpagU.gif"
    - "When I’m finally done with my task https://ljdchost.com/inoDg77.gif"
    - "When I’m working on the same error since this morning https://ljdchost.com/zpBxWfY.gif"
    - "When they force me to go to a customers meeting https://ljdchost.com/z2YOaCT.gif"
    - "When my code is compiling https://ljdchost.com/TIzi8oQ.gif"
    - "When they ask me if I’m the last one who commited https://ljdchost.com/FmUYfRq.gif"
    - "When my new quickfix still doesn’t work https://ljdchost.com/ciJjgn5.gif"
    - "When I come to help a colleague on a problem https://ljdchost.com/ut9aYgA.gif"
    - "When I realize that I deleted production data https://ljdchost.com/Eaqaqxr.gif"
    - "When they want me to write functional specifications https://ljdchost.com/iLuTupC.gif"
    - "When the intern starts his presentation https://ljdchost.com/fVDMe5V.gif"
    - "When they show me a bug I’m responsible of https://ljdchost.com/Ish1fUH.gif"
    - "When I finished coding my feature on time https://ljdchost.com/4mcbG13.gif"
    - "When we learn that the sales guy sold an IE compatibility https://ljdchost.com/CEjAxJM.gif"
    - "When I receive specs entirely written in Comic Sans https://ljdchost.com/dgzhgcL.gif"
    - "An error occurred… https://ljdchost.com/Gq02ZfQ.gif"
    - "When I leave the office after my production delivery completely failed https://ljdchost.com/ESgvnZ5.gif"
    - "When I’m in charge of customer support during a huge production incident https://ljdchost.com/DEFowUt.gif"
    - "When I’ve been working on the same bug for 3 damn hours https://ljdchost.com/zA3F72f.gif"
    - "When I’m done with my demo and no bug showed up https://ljdchost.com/Kmewyl4.gif"
    - "When the sales guy lets the intern speak in a meeting https://ljdchost.com/dC4mjg7.gif"
    - "When the sysadmin comes to see me https://ljdchost.com/km5F9OQ.gif"
    - "0 integration tests. https://ljdchost.com/ElpBZKE.gif"
    - "When they tell me that I’m free to select the technology of my choice https://ljdchost.com/ukZ1kAP.gif"
    - "When the sales guy tells the customer that we will deliver his new feature in 2 days https://ljdchost.com/L1HzkmZ.gif"
    - "When the intern broke everything in my project https://ljdchost.com/vEKPc7F.gif"
    - "When I take a strong coffee before a hard debug session https://ljdchost.com/fXUbedd.gif"
    - "When they ask me to work on an old VB app https://ljdchost.com/mIfEn3s.gif"